### ISSUE TITLE
Provider attempts to re-create existing cluster when specified SSH key file is missing

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [yamamoto-febc/terraform-provider-rke#66] opened 2019-03-05 15:55 UTC
We got this situation, that SSH key file we use for creating cluster got moved to a different path. This resulted in Terraform attempting to re-create the cluster and when I did `terraform refresh`, cluster got removed from state file.

I believe this is a bug and provider should complain, that file does not exist, even though with it should not be able to connect to cluster nodes without correct SSH key file.

Steps to reproduce:
- Generate SSH key file:
  ```
  ssh-keygen -b 4096 -t rsa -f ./id_rsa -q -N ""
  ```
- Create `test.tf` file with minimal cluster configuration:
  ```
  provider "rke" {
    version = "~> 0.8.0"
  }
  
  resource rke_cluster "cluster" {
    ssh_key_path = "${path.root}/id_rsa"
  
    nodes {
        address = "x.x.x.x"
        user    = "root"
        role    = ["controlplane", "worker", "etcd"]
    }
  }
  ```
- create cluster with `terraform apply`
- verify that cluster is there with `terraform state list`
- move SSH key file:
  ```
  mv id_rsa id_rsa_test
  ```
- at this point, running `terraform apply` attempts to re-create a cluster, without any warnings
- running `terraform refresh` **removes cluster from state file**

**Comment by yamamoto-febc** [comment] 2019-03-06 02:22
Hi @mateusz-gozdek-sociomantic, Thank you for your reporting.
  
It is expected behavior at the moment.

When executing plan, apply and refresh, this provider works as follows:

- Read cluster state via SSH(using stored keys in state).
- If can't reach to nodes, this provider remove cluster from state.
- If you execute apply with this condition, this provider attempts re-create cluster newly.

In your reported case, you modified ssh-key directly.
So this provider can't retrive cluster state via SSH - cluster will be removed from state.

**Comment by mateusz-gozdek-sociomantic** [comment] 2019-03-06 08:27
Hey @yamamoto-febc, thanks for quick feedback. This behaviour was quite surprising for me. I also noticed, that when you want to rename the key file, but old and new keys must be present, otherwise it attempts to re-create a cluster too, meaning this needs to be done in 2 steps to be graceful.

Still, I'm under impression, that rather than blindly re-create the cluster, refresh should fail when it's not able to find the key, if cluster already exists in the state, as that means something is not quite right. But if you are sure, that this is intentional behaviour, feel free to close the issue. At least the behaviour is now documented :)

I spend few hours trying to figure out what happened here, as this problem also combined with the other one, as when cluster will be removed from state and you use cluster output data for `kubernetes` provider, that one is not able to connect to cluster anymore, as it tried to connect to `localhost` (but I guess is just limitation of Terraform). If someone hits the same problem, the solution is to persist `kube_cluster_config.yaml` file to Terraform repo (ideally encrypted) and then reconfigure `kubernetes` provider to use that file instead of data from `rke_cluster`. Otherwise both planning and actual graceful destroy of the cluster is not possible.

Also great thanks @yamamoto-febc for your work on this provider, as for me, this is the smoothest experience with deploying kubernetes to VMs/bare metal in automated fashion!

**Comment by yamamoto-febc** [comment] 2019-03-06 11:00
I'm sorry you've come across this issue.

I think that this issue implies that the stance of how to use Terraform is different among us.
So I will explain my stance.

---

Generally, we recommend that don't manually change the resources managed by Terraform except Terraform.
If it still needs modify, it will go out of Terraform management.

This means that editing tfstate(and etc) needs to be done as a responsibility of the user if necessary.

---

In this issue's case, Terraform has not been able to detect changes because the SSH key has been changed without being under Terraform control. 
Therefore, the RKE provider can not connect to cluster by `refresh` operation and attempts to delete the cluster.

According to my stance I wrote, It is the user's responsibility to make available to connect the server via SSH using new ssh key.

(However, only in this case, Terraform will be able to detect changes by using `ssh_key` instead of `ssh_key_path` as follows. - Because the contents of the ssh key will be under Terraform control)

```hcl
resource rke_cluster "cluster" {
  nodes {
      address = "x.x.x.x"
      user    = "root"
      role    = ["controlplane", "worker", "etcd"]
      ssh_key = "${file("${path.root}/id_rsa")}" # insted of ssh_key_path
  }
}
```

Now, I'm going to close this, but any suggestions are welcome if you have!
Thank you again @mateusz-gozdek-sociomantic for your great contribution:+1:

**Closed by yamamoto-febc** 2019-03-06 11:00 UTC

**Comment by mateusz-gozdek-sociomantic** [comment] 2019-03-06 11:09
Just to complete your solution @yamamoto-febc, one can use Terraform to generate and manage SSH keys with following code:
```
provider "tls" {}
resource "tls_private_key" "terraform" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
```

Then when specifying the node, use:
```
ssh_key           = "${tls_private_key.terraform.private_key_pem}"
```

or when #60 is solved, set it globally on cluster. Then SSH key is stored in tfstate file, so this issue should never happen.
