### ISSUE TITLE
Multiple nodes throws error

### ISSUE THREAD

**Issue by jaxxstorm** [yamamoto-febc/terraform-provider-rke#31] opened 2018-10-19 23:33 UTC
I'm trying to do multiple knows as per the example:
```
variable "node_addrs" {
  type    = "list"
  default = ["192.2.0.1", "192.2.0.2"]
}

data rke_node_parameter "nodes" {
  count   = "${length(var.node_addrs)}"

  address = "${var.node_addrs[count.index]}"
  user    = "ubuntu"
  role    = ["controlplane", "worker", "etcd"]
  ssh_key = "${file("~/.ssh/id_rsa")}"
}

resource rke_cluster "cluster" {
  nodes_conf = ["${data.rke_node_parameter.nodes.*.json}"]
}
```

However, it's throwing this error:

```
data.rke_node_parameter.nodes: value of 'count' cannot be computed
```

**Comment by yamamoto-febc** [comment] 2018-10-20 03:11
Hi @jaxxstorm,

I could't reproduce this error:thinking:

I tried this at following environments:

```
$ terraform version
Terraform v0.11.8
+ provider.rke v0.4.0
```

What version of `terraform` + `provider.rke` do you use?

**Comment by yamamoto-febc** [comment] 2018-10-22 10:40
I retried it with Terraform v0.11.2, but I have not yet reproduced this error:thinking:

In this multiple node example seems that all of `validate`/`plan`/`apply`/`destroy` operations works as expected.

Can you provide some more information? 
Are there any errors in the logs, or other operations involved here?

**Comment by yamamoto-febc** [comment] 2018-12-01 04:48
I'm going to close this issue because I couldn't reproduce.
If still occur this error, please re-open the issue.

**Closed by yamamoto-febc** 2018-12-01 04:48 UTC
